#define TERM_END_OF_FILE                     1
#define TERM_INCLUDE                         2
#define TERM_STRING_VALUE                    3
#define TERM_CPP_INCLUDE                     4
#define TERM_NAMESPACE                       5
#define TERM_IDENTIFIER                      6
#define TERM_LISTSEP                         7
#define TERM_DOC_COMMENT                     8
#define TERM_CONST                           9
#define TERM_EQ                             10
#define TERM_TYPEDEF                        11
#define TERM_ENUM                           12
#define TERM_CURLY_OPEN                     13
#define TERM_CURLY_CLOSE                    14
#define TERM_INTEGER_VALUE                  15
#define TERM_UNION                          16
#define TERM_EXCEPTION                      17
#define TERM_STRUCT                         18
#define TERM_COLON                          19
#define TERM_REQUIRED                       20
#define TERM_OPTIONAL                       21
#define TERM_SERVICE                        22
#define TERM_EXTENDS                        23
#define TERM_PAREN_OPEN                     24
#define TERM_PAREN_CLOSE                    25
#define TERM_ONEWAY                         26
#define TERM_VOID                           27
#define TERM_THROWS                         28
#define TERM_BOOL                           29
#define TERM_BYTE                           30
#define TERM_I16                            31
#define TERM_I32                            32
#define TERM_I64                            33
#define TERM_DOUBLE                         34
#define TERM_STRING                         35
#define TERM_BINARY                         36
#define TERM_MAP                            37
#define TERM_LT                             38
#define TERM_GT                             39
#define TERM_SET                            40
#define TERM_LIST                           41
#define TERM_DOUBLE_VALUE                   42
#define TERM_BRACKET_OPEN                   43
#define TERM_BRACKET_CLOSE                  44
